package io.warpnect.video.decoder

data class VideoDecoderSnapshot(
    val state: VideoDecoderState = VideoDecoderState.Stopped,
    val codec: VideoDecoderCodec? = null,
    val codecName: String? = null,
    val canonicalCodecName: String? = null,
    val hardwareAcceleration: VideoDecoderHardwareAcceleration = VideoDecoderHardwareAcceleration.Unknown,
    val lowLatencyFeatureSupported: Boolean? = null,
    val lowLatencyRequested: Boolean = false,
    val width: Int? = null,
    val height: Int? = null,
    val activeConfigGeneration: Long? = null,
    val accessUnitsQueued: Long = 0,
    val encodedBytesQueued: Long = 0,
    val inputBackpressureEvents: Long = 0,
    val inputBufferTooSmall: Long = 0,
    val decodedOutputBuffers: Long = 0,
    val framesRenderedRequested: Long = 0,
    val framesDropped: Long = 0,
    val framesRenderScheduled: Long = 0,
    val outputFormatChanges: Long = 0,
    val codecErrors: Long = 0,
    val lastInputPtsUs: Long? = null,
    val lastOutputPtsUs: Long? = null,
    val frameRenderedCallbacks: Long = 0,
    val lastRenderedPtsUs: Long? = null,
    val lastRenderedNanoTime: Long? = null,
    val prepareLatencyUs: Long? = null,
    val lastCodecDiagnosticInfo: String? = null,
    val lastCodecErrorRecoverable: Boolean? = null,
    val lastCodecErrorTransient: Boolean? = null,
    val lastError: VideoDecoderError = VideoDecoderError.None,
)
