package io.warpnect.audio.playback

import io.warpnect.audio.capture.AudioCaptureSource

data class AudioPlaybackSnapshot(
    val state: AudioPlaybackState = AudioPlaybackState.Stopped,
    val source: AudioCaptureSource? = null,
    val configGeneration: Long = 0,
    val requestedSampleRateHz: Int = 0,
    val actualSampleRateHz: Int = 0,
    val requestedChannelCount: Int = 0,
    val actualChannelCount: Int = 0,
    val frameDurationUs: Int = 0,
    val framesPerCodecFrame: Int = 0,
    val requestedPerformanceMode: AudioPlaybackPerformanceMode = AudioPlaybackPerformanceMode.LowLatency,
    val actualPerformanceMode: AudioPlaybackPerformanceMode = AudioPlaybackPerformanceMode.Unknown,
    val requestedSharingMode: AudioPlaybackSharingMode = AudioPlaybackSharingMode.Exclusive,
    val actualSharingMode: AudioPlaybackSharingMode = AudioPlaybackSharingMode.Unknown,
    val audioApi: AudioPlaybackApi = AudioPlaybackApi.Unknown,
    val requestedBufferBursts: Int = 0,
    val framesPerBurst: Int = 0,
    val requestedBufferFrames: Int = 0,
    val actualBufferFrames: Int = 0,
    val bufferCapacityFrames: Int = 0,
    val hardwareSampleRateHz: Int = 0,
    val hardwareChannelCount: Int = 0,
    val ringCapacityFrames: Int = 0,
    val ringOccupancyFrames: Int = 0,
    val ringHighWaterMark: Int = 0,
    val pcmFramesSubmitted: Long = 0,
    val pcmFramesConsumed: Long = 0,
    val pcmFramesRejected: Long = 0,
    val underrunCallbacks: Long = 0,
    val underrunFrames: Long = 0,
    val silenceFramesInserted: Long = 0,
    val xRunCount: Int = 0,
    val normalFrames: Long = 0,
    val plcFrames: Long = 0,
    val discontinuityFrames: Long = 0,
    val lastSourceFramePosition: Long = 0,
    val lastCaptureTimeUs: Long = 0,
    val lastPresentationFramePosition: Long = 0,
    val lastPresentationTimeNs: Long = 0,
    val presentationTimestampValid: Boolean = false,
    val exclusiveRequestGranted: Boolean = false,
    val actualFormat: AudioPlaybackPcmFormat = AudioPlaybackPcmFormat.Unknown,
    val hardwareFormat: AudioPlaybackPcmFormat = AudioPlaybackPcmFormat.Unknown,
    val ringResidenceSamples: Long = 0,
    val lastRingResidenceNs: Long = 0,
    val maxRingResidenceNs: Long = 0,
    val lastError: AudioPlaybackError = AudioPlaybackError.None,
)
