# CMake generated Testfile for 
# Source directory: C:/Users/Francy/Desktop/Warpnect/native
# Build directory: C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_header_compile_test]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_header_compile_test.exe")
  set_tests_properties([=[scl_header_compile_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;338;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_header_compile_test]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_header_compile_test.exe")
  set_tests_properties([=[scl_header_compile_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;338;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_header_compile_test]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_header_compile_test.exe")
  set_tests_properties([=[scl_header_compile_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;338;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_header_compile_test]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_header_compile_test.exe")
  set_tests_properties([=[scl_header_compile_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;338;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_header_compile_test]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_packet_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_packet_tests.exe")
  set_tests_properties([=[scl_packet_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;339;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_packet_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_packet_tests.exe")
  set_tests_properties([=[scl_packet_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;339;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_packet_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_packet_tests.exe")
  set_tests_properties([=[scl_packet_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;339;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_packet_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_packet_tests.exe")
  set_tests_properties([=[scl_packet_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;339;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_packet_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_udp_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_udp_tests.exe")
  set_tests_properties([=[scl_udp_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;340;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_udp_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_udp_tests.exe")
  set_tests_properties([=[scl_udp_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;340;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_udp_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_udp_tests.exe")
  set_tests_properties([=[scl_udp_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;340;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_udp_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_udp_tests.exe")
  set_tests_properties([=[scl_udp_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;340;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_udp_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_fragmentation_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_fragmentation_tests.exe")
  set_tests_properties([=[scl_fragmentation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;341;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_fragmentation_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_fragmentation_tests.exe")
  set_tests_properties([=[scl_fragmentation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;341;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_fragmentation_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_fragmentation_tests.exe")
  set_tests_properties([=[scl_fragmentation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;341;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_fragmentation_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_fragmentation_tests.exe")
  set_tests_properties([=[scl_fragmentation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;341;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_fragmentation_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_recovery_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_recovery_tests.exe")
  set_tests_properties([=[scl_recovery_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;342;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_recovery_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_recovery_tests.exe")
  set_tests_properties([=[scl_recovery_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;342;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_recovery_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_recovery_tests.exe")
  set_tests_properties([=[scl_recovery_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;342;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_recovery_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_recovery_tests.exe")
  set_tests_properties([=[scl_recovery_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;342;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_recovery_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_fec_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_fec_tests.exe")
  set_tests_properties([=[scl_fec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;343;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_fec_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_fec_tests.exe")
  set_tests_properties([=[scl_fec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;343;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_fec_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_fec_tests.exe")
  set_tests_properties([=[scl_fec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;343;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_fec_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_fec_tests.exe")
  set_tests_properties([=[scl_fec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;343;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_fec_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_timing_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_timing_telemetry_tests.exe")
  set_tests_properties([=[scl_timing_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;344;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_timing_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_timing_telemetry_tests.exe")
  set_tests_properties([=[scl_timing_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;344;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_timing_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_timing_telemetry_tests.exe")
  set_tests_properties([=[scl_timing_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;344;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_timing_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_timing_telemetry_tests.exe")
  set_tests_properties([=[scl_timing_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;344;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_timing_telemetry_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_phase1_integration_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_phase1_integration_tests.exe")
  set_tests_properties([=[scl_phase1_integration_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;345;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_phase1_integration_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_phase1_integration_tests.exe")
  set_tests_properties([=[scl_phase1_integration_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;345;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_phase1_integration_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_phase1_integration_tests.exe")
  set_tests_properties([=[scl_phase1_integration_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;345;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_phase1_integration_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_phase1_integration_tests.exe")
  set_tests_properties([=[scl_phase1_integration_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;345;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_phase1_integration_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_video_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_video_transport_tests.exe")
  set_tests_properties([=[scl_video_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;346;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_video_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_video_transport_tests.exe")
  set_tests_properties([=[scl_video_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;346;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_video_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_video_transport_tests.exe")
  set_tests_properties([=[scl_video_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;346;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_video_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_video_transport_tests.exe")
  set_tests_properties([=[scl_video_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;346;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_video_transport_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_video_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_video_runtime_tests.exe")
  set_tests_properties([=[scl_video_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;347;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_video_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_video_runtime_tests.exe")
  set_tests_properties([=[scl_video_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;347;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_video_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_video_runtime_tests.exe")
  set_tests_properties([=[scl_video_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;347;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_video_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_video_runtime_tests.exe")
  set_tests_properties([=[scl_video_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;347;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_video_runtime_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_video_resync_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_video_resync_tests.exe")
  set_tests_properties([=[scl_video_resync_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;348;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_video_resync_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_video_resync_tests.exe")
  set_tests_properties([=[scl_video_resync_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;348;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_video_resync_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_video_resync_tests.exe")
  set_tests_properties([=[scl_video_resync_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;348;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_video_resync_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_video_resync_tests.exe")
  set_tests_properties([=[scl_video_resync_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;348;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_video_resync_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[opus_audio_encoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/opus_audio_encoder_tests.exe")
  set_tests_properties([=[opus_audio_encoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;349;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[opus_audio_encoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/opus_audio_encoder_tests.exe")
  set_tests_properties([=[opus_audio_encoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;349;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[opus_audio_encoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/opus_audio_encoder_tests.exe")
  set_tests_properties([=[opus_audio_encoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;349;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[opus_audio_encoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/opus_audio_encoder_tests.exe")
  set_tests_properties([=[opus_audio_encoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;349;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[opus_audio_encoder_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[opus_audio_decoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/opus_audio_decoder_tests.exe")
  set_tests_properties([=[opus_audio_decoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;350;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[opus_audio_decoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/opus_audio_decoder_tests.exe")
  set_tests_properties([=[opus_audio_decoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;350;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[opus_audio_decoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/opus_audio_decoder_tests.exe")
  set_tests_properties([=[opus_audio_decoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;350;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[opus_audio_decoder_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/opus_audio_decoder_tests.exe")
  set_tests_properties([=[opus_audio_decoder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;350;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[opus_audio_decoder_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[audio_playback_ring_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/audio_playback_ring_tests.exe")
  set_tests_properties([=[audio_playback_ring_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;351;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[audio_playback_ring_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/audio_playback_ring_tests.exe")
  set_tests_properties([=[audio_playback_ring_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;351;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[audio_playback_ring_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/audio_playback_ring_tests.exe")
  set_tests_properties([=[audio_playback_ring_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;351;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[audio_playback_ring_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/audio_playback_ring_tests.exe")
  set_tests_properties([=[audio_playback_ring_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;351;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[audio_playback_ring_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_audio_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_audio_transport_tests.exe")
  set_tests_properties([=[scl_audio_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;352;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_audio_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_audio_transport_tests.exe")
  set_tests_properties([=[scl_audio_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;352;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_audio_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_audio_transport_tests.exe")
  set_tests_properties([=[scl_audio_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;352;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_audio_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_audio_transport_tests.exe")
  set_tests_properties([=[scl_audio_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;352;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_audio_transport_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_audio_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_audio_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_audio_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;353;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_audio_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_audio_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_audio_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;353;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_audio_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_audio_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_audio_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;353;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_audio_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_audio_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_audio_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;353;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_audio_receiver_runtime_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_input_protocol_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_input_protocol_tests.exe")
  set_tests_properties([=[scl_input_protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;354;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_input_protocol_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_input_protocol_tests.exe")
  set_tests_properties([=[scl_input_protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;354;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_input_protocol_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_input_protocol_tests.exe")
  set_tests_properties([=[scl_input_protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;354;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_input_protocol_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_input_protocol_tests.exe")
  set_tests_properties([=[scl_input_protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;354;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_input_protocol_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_input_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_input_transport_tests.exe")
  set_tests_properties([=[scl_input_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;355;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_input_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_input_transport_tests.exe")
  set_tests_properties([=[scl_input_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;355;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_input_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_input_transport_tests.exe")
  set_tests_properties([=[scl_input_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;355;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_input_transport_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_input_transport_tests.exe")
  set_tests_properties([=[scl_input_transport_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;355;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_input_transport_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_input_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_input_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_input_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;356;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_input_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_input_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_input_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;356;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_input_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_input_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_input_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;356;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_input_receiver_runtime_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_input_receiver_runtime_tests.exe")
  set_tests_properties([=[scl_input_receiver_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;356;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_input_receiver_runtime_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_session_protection_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_session_protection_tests.exe")
  set_tests_properties([=[scl_session_protection_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;357;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_session_protection_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_session_protection_tests.exe")
  set_tests_properties([=[scl_session_protection_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;357;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_session_protection_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_session_protection_tests.exe")
  set_tests_properties([=[scl_session_protection_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;357;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_session_protection_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_session_protection_tests.exe")
  set_tests_properties([=[scl_session_protection_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;357;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_session_protection_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_runtime_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_runtime_telemetry_tests.exe")
  set_tests_properties([=[scl_runtime_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;358;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_runtime_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_runtime_telemetry_tests.exe")
  set_tests_properties([=[scl_runtime_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;358;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_runtime_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_runtime_telemetry_tests.exe")
  set_tests_properties([=[scl_runtime_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;358;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_runtime_telemetry_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_runtime_telemetry_tests.exe")
  set_tests_properties([=[scl_runtime_telemetry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;358;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_runtime_telemetry_tests]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[scl_diagnostic_event_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Debug/scl_diagnostic_event_tests.exe")
  set_tests_properties([=[scl_diagnostic_event_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;359;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[scl_diagnostic_event_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/Release/scl_diagnostic_event_tests.exe")
  set_tests_properties([=[scl_diagnostic_event_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;359;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[scl_diagnostic_event_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/MinSizeRel/scl_diagnostic_event_tests.exe")
  set_tests_properties([=[scl_diagnostic_event_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;359;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[scl_diagnostic_event_tests]=] "C:/Users/Francy/Desktop/Warpnect/native/build-rfc006e/RelWithDebInfo/scl_diagnostic_event_tests.exe")
  set_tests_properties([=[scl_diagnostic_event_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;359;add_test;C:/Users/Francy/Desktop/Warpnect/native/CMakeLists.txt;0;")
else()
  add_test([=[scl_diagnostic_event_tests]=] NOT_AVAILABLE)
endif()
subdirs("mbedtls-3.6.7")
subdirs("opus-1.6.1")
