package io.warpnect.video.encoder

data class VideoEncoderSnapshot(
    val state: VideoEncoderState = VideoEncoderState.Stopped,
    val codec: VideoCodec? = null,
    val codecName: String? = null,
    val canonicalCodecName: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val targetFrameRate: Int? = null,
    val targetBitrateBps: Int? = null,
    val bitrateMode: VideoBitrateMode? = null,
    val hardwareAcceleration: VideoEncoderHardwareAcceleration = VideoEncoderHardwareAcceleration.Unknown,
    val requestedLatencyFrames: Int? = null,
    val reportedLatencyFrames: Int? = null,
    val outputReorderDepth: Int? = null,
    val accessUnitsEncoded: Long = 0,
    val encodedBytes: Long = 0,
    val keyFramesEncoded: Long = 0,
    val codecConfigBuffers: Long = 0,
    val outputFormatChanges: Long = 0,
    val runtimeErrors: Long = 0,
    val lastPresentationTimeUs: Long? = null,
    val firstAccessUnitAtMonotonicUs: Long? = null,
    val prepareLatencyUs: Long? = null,
    val lastCodecDiagnosticInfo: String? = null,
    val lastCodecErrorRecoverable: Boolean? = null,
    val lastCodecErrorTransient: Boolean? = null,
    val lastError: VideoEncoderError = VideoEncoderError.None,
)
