#include "clock_sync.h"
#include "clock_sync_control.h"
#include "datagram_limits.h"
#include "fec.h"
#include "fec_control.h"
#include "fec_result.h"
#include "fragment_result.h"
#include "fragmentation.h"
#include "input_protocol.h"
#include "loss_detector.h"
#include "monotonic_time.h"
#include "native_bridge.h"
#include "packet_codec.h"
#include "packet_result.h"
#include "protocol.h"
#include "reassembly.h"
#include "recovery_control.h"
#include "recovery_result.h"
#include "reed_solomon.h"
#include "retransmission_cache.h"
#include "sequence_number.h"
#include "telemetry.h"
#include "timing_result.h"
#include "udp_endpoint.h"
#include "udp_engine.h"
#include "udp_result.h"
#include "udp_socket.h"
#include "video_packetizer.h"
#include "video_protocol.h"
#include "video_result.h"
#include "video_transport.h"

static_assert(__cplusplus >= 202002L, "Warpnect native host targets require C++20 or newer.");

int main() {
    return 0;
}
