package io.warpnect.debug.input

import android.app.Activity
import android.content.ComponentName
import android.content.ServiceConnection
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.Process
import android.util.Log
import android.view.KeyEvent
import android.view.MotionEvent
import android.widget.TextView
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger
import rikka.shizuku.Shizuku

/**
 * Debug-only owned foreground target for bounded privileged-input API investigation.
 * It has no application data and only observes F1 and touch events generated by its paired probe.
 */
class InputApiForensicsActivity : Activity() {
    private val started = AtomicBoolean(false)
    private val serviceConnected = AtomicBoolean(false)
    private val observedKeyEvents = AtomicInteger(0)
    private val observedTouchEvents = AtomicInteger(0)
    private val observedPointerEvents = AtomicInteger(0)
    private val observedJoystickEvents = AtomicInteger(0)
    private var connection: ServiceConnection? = null
    private lateinit var args: Shizuku.UserServiceArgs

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(TextView(this).apply { text = "Warpnect input API diagnostics" })
        args = Shizuku.UserServiceArgs(
            ComponentName(packageName, InputApiForensicsUserService::class.java.name),
        )
            .daemon(false)
            .debuggable(true)
            .processNameSuffix("input-forensics")
            .tag("input-forensics")
            .version(SERVICE_VERSION)
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)
        if (hasFocus && started.compareAndSet(false, true)) startProbe()
    }

    override fun onKeyDown(keyCode: Int, event: KeyEvent): Boolean {
        if (keyCode == KeyEvent.KEYCODE_F1) {
            observedKeyEvents.incrementAndGet()
            Log.i(TAG, "INPUT_FORENSICS_TARGET_KEY_OBSERVED key=F1")
            return true
        }
        return super.onKeyDown(keyCode, event)
    }

    override fun dispatchTouchEvent(event: MotionEvent): Boolean {
        if (event.actionMasked == MotionEvent.ACTION_DOWN) {
            observedTouchEvents.incrementAndGet()
            Log.i(TAG, "INPUT_FORENSICS_TARGET_TOUCH_OBSERVED")
            return true
        }
        return super.dispatchTouchEvent(event)
    }

    override fun onGenericMotionEvent(event: MotionEvent): Boolean = when {
        event.isFromSource(android.view.InputDevice.SOURCE_MOUSE) -> {
            observedPointerEvents.incrementAndGet()
            Log.i(TAG, "INPUT_FORENSICS_TARGET_POINTER_OBSERVED")
            true
        }
        event.isFromSource(android.view.InputDevice.SOURCE_JOYSTICK) -> {
            observedJoystickEvents.incrementAndGet()
            Log.i(TAG, "INPUT_FORENSICS_TARGET_JOYSTICK_OBSERVED")
            true
        }
        else -> super.onGenericMotionEvent(event)
    }

    override fun onDestroy() {
        connection?.let { runCatching { Shizuku.unbindUserService(args, it, true) } }
        super.onDestroy()
    }

    private fun startProbe() {
        if (!runCatching { Shizuku.pingBinder() }.getOrDefault(false)) {
            Log.i(TAG, "INPUT_FORENSICS_MAIN_SHIZUKU_NOT_RUNNING")
            finish()
            return
        }
        val granted = runCatching { Shizuku.checkSelfPermission() }.getOrDefault(-1) ==
            android.content.pm.PackageManager.PERMISSION_GRANTED
        if (!granted) {
            Log.i(TAG, "INPUT_FORENSICS_MAIN_PERMISSION_REQUIRED")
            finish()
            return
        }
        val localPid = Process.myPid()
        val localUid = Process.myUid()
        Log.i(TAG, "INPUT_FORENSICS_MAIN_READY pid=$localPid uid=$localUid display=${display?.displayId ?: 0}")
        val activeConnection = object : ServiceConnection {
            override fun onServiceConnected(name: ComponentName, binder: IBinder) {
                serviceConnected.set(true)
                connection = this
                val service = IInputApiForensicsService.Stub.asInterface(binder)
                Thread {
                    val inspection = runCatching { service.inspect() }.getOrElse {
                        Bundle().apply { putString("status", "INSPECT_REMOTE_FAILURE") }
                    }
                    logBundle("SERVICE_INSPECTION", inspection)
                    val displayId = display?.displayId ?: 0
                    val key = runCatching { service.injectTestKey(displayId) }.getOrElse {
                        Bundle().apply { putString("status", "KEY_REMOTE_FAILURE") }
                    }
                    logBundle("KEY_RESULT", key)
                    Thread.sleep(300)
                    val x = window.decorView.width.coerceAtLeast(1) / 2f
                    val y = window.decorView.height.coerceAtLeast(1) / 2f
                    val touch = runCatching { service.injectTestTouch(displayId, x, y) }.getOrElse {
                        Bundle().apply { putString("status", "TOUCH_REMOTE_FAILURE") }
                    }
                    logBundle("TOUCH_RESULT", touch)
                    Thread.sleep(250)
                    val pointer = runCatching { service.injectTestPointer(displayId, x, y) }.getOrElse {
                        Bundle().apply { putString("status", "POINTER_REMOTE_FAILURE") }
                    }
                    logBundle("POINTER_RESULT", pointer)
                    Thread.sleep(250)
                    val joystick = runCatching { service.injectTestJoystick(displayId) }.getOrElse {
                        Bundle().apply { putString("status", "JOYSTICK_REMOTE_FAILURE") }
                    }
                    logBundle("JOYSTICK_RESULT", joystick)
                    Thread.sleep(250)
                    Log.i(
                        TAG,
                        "INPUT_FORENSICS_OBSERVED key=${observedKeyEvents.get()} touch=${observedTouchEvents.get()} " +
                            "pointer=${observedPointerEvents.get()} joystick=${observedJoystickEvents.get()}",
                    )
                    runCatching { Shizuku.unbindUserService(args, this, true) }
                    connection = null
                    runOnUiThread(::finish)
                }.start()
            }

            override fun onServiceDisconnected(name: ComponentName) {
                Log.i(TAG, "INPUT_FORENSICS_USER_SERVICE_DISCONNECTED")
            }
        }
        try {
            Shizuku.bindUserService(args, activeConnection)
            Handler(Looper.getMainLooper()).postDelayed({
                if (!serviceConnected.get()) {
                    Log.i(TAG, "INPUT_FORENSICS_USER_SERVICE_BIND_TIMEOUT")
                    runCatching { Shizuku.unbindUserService(args, activeConnection, false) }
                    finish()
                }
            }, USER_SERVICE_BIND_TIMEOUT_MS)
        } catch (_: RuntimeException) {
            Log.i(TAG, "INPUT_FORENSICS_USER_SERVICE_BIND_FAILED")
            finish()
        }
    }

    private fun logBundle(name: String, bundle: Bundle) {
        val values = bundle.keySet().sorted().joinToString(" ") { key -> "$key=${bundle.get(key)}" }
        Log.i(TAG, "INPUT_FORENSICS_$name $values")
    }

    private companion object {
        const val SERVICE_VERSION = 1
        const val USER_SERVICE_BIND_TIMEOUT_MS = 20_000L
        const val TAG = "WarpnectInputForensics"
    }
}
